//! Cut markers (GM-5.3, ADR-07): facts about edges that no static resolution can
//! follow. Orthogonal to confidence — a cut marker is never part of the
//! five-value edge-condition set and never silently drops the edge.

use serde::{Deserialize, Serialize};

/// A reason an edge's target is structurally hard or impossible to resolve.
/// An edge may carry zero or more of these (see [`CutMarkers`]).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
#[repr(u8)]
pub enum CutMarker {
    /// Call target is a string computed at runtime (reflection, `eval`).
    Reflective = 0,
    /// Dispatches through a runtime plugin, script, or dynamic loader.
    Dynamic = 1,
    /// Binding is managed by a dependency-injection container.
    ViaDi = 2,
    /// Call crosses a foreign-function boundary (JNI, Rust `extern "C"`).
    ViaFfi = 3,
    /// Resolution was attempted and produced no candidates.
    Unresolved = 4,
    /// Call edges may exist inside code generated by an unexpanded proc macro at
    /// this site; expansion was not performed (ADR-07, GM-5.3).
    UnexpandedMacro = 5,
    /// Dataflow through a call site whose callee summary is not yet computed
    /// (design §1.1). The intraprocedural pass records the cut rather than
    /// asserting a false cross-function `DerivesFrom` edge; SC4 resolves it
    /// through the callee's IFDS summary.
    OpaqueCall = 6,
    /// A field access path deeper than depth 1 (`u.cfg.timeout`) truncated to its
    /// base value node (design §1.2). The flow to the base is recorded; the
    /// deeper path component is the cut.
    TruncatedAccessPath = 7,
    /// The IFDS interprocedural-summary pass hit its per-SCC or per-index
    /// work-budget cap (`DEFAULT_MAX_SUMMARY_EDGES`, v0.3 SC4) before reaching a
    /// summary fixpoint. The materialized `DerivesFrom` edge set is sound but
    /// possibly incomplete past this point — recorded honestly rather than
    /// hanging on an adversarial dense/deep call graph (design §C, mirroring the
    /// bounded-DFS backstop in cgx-query). No further interproc edges are minted
    /// once the cap fires.
    SummaryBudgetExceeded = 8,
}

impl CutMarker {
    pub const ALL: [CutMarker; 9] = [
        CutMarker::Reflective,
        CutMarker::Dynamic,
        CutMarker::ViaDi,
        CutMarker::ViaFfi,
        CutMarker::Unresolved,
        CutMarker::UnexpandedMacro,
        CutMarker::OpaqueCall,
        CutMarker::TruncatedAccessPath,
        CutMarker::SummaryBudgetExceeded,
    ];
}

/// A deterministic, deduplicated set of cut markers on an edge.
///
/// Stored as a sorted `SmallVec` rather than a `HashSet` so the canonical
/// postcard encoding is byte-identical across runs (no hash-order leak).
#[derive(Debug, Clone, Default, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct CutMarkers(smallvec::SmallVec<[CutMarker; 2]>);

impl CutMarkers {
    /// An empty marker set.
    pub fn new() -> Self {
        CutMarkers(smallvec::SmallVec::new())
    }

    /// Build a canonical (sorted, deduplicated) set from any iterator of markers.
    pub fn from_iter_canonical<I: IntoIterator<Item = CutMarker>>(iter: I) -> Self {
        let mut v: smallvec::SmallVec<[CutMarker; 2]> = iter.into_iter().collect();
        v.sort_unstable();
        v.dedup();
        CutMarkers(v)
    }

    /// Insert a marker, preserving the sorted-deduplicated invariant.
    pub fn insert(&mut self, marker: CutMarker) {
        if let Err(pos) = self.0.binary_search(&marker) {
            self.0.insert(pos, marker);
        }
    }

    /// Whether a given marker is present.
    pub fn contains(&self, marker: CutMarker) -> bool {
        self.0.binary_search(&marker).is_ok()
    }

    /// Whether the set is empty.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// The markers in canonical (sorted) order.
    pub fn iter(&self) -> impl Iterator<Item = CutMarker> + '_ {
        self.0.iter().copied()
    }

    /// Number of markers in the set.
    pub fn len(&self) -> usize {
        self.0.len()
    }
}
