// Code generated by schemagen from tools.json. DO NOT EDIT.

package cgx

import "context"

// SchemaHash is the SHA-1 of the tool schema document the types were
// generated from. The engine reports the hash of its own; they must match.
const SchemaHash = "f9eea02127d5ca6f59d5dafca20d73e893164957"

// Tool names.
const (
	ToolCallers       = "callers"
	ToolCallees       = "callees"
	ToolReaches       = "reaches"
	ToolPaths         = "paths"
	ToolUnused        = "unused"
	ToolExplain       = "explain"
	ToolSearch        = "search"
	ToolSymbols       = "symbols"
	ToolFlowsTo       = "flows_to"
	ToolFlowsFrom     = "flows_from"
	ToolGraphQuery    = "graph_query"
	ToolCoupling      = "coupling"
	ToolImpactedTests = "impacted_tests"
)

// Callers runs the engine's "callers" tool on the graph g holds. req carries the
// tool's arguments; the result is its structuredContent, decoded. A query that
// the engine rejects returns a *ToolError.
func (g *Graph) Callers(ctx context.Context, req CallersRequest) (*CallersResult, error) {
	return call[CallersResult](ctx, g, ToolCallers, req)
}

// Callees runs the engine's "callees" tool on the graph g holds. req carries the
// tool's arguments; the result is its structuredContent, decoded. A query that
// the engine rejects returns a *ToolError.
func (g *Graph) Callees(ctx context.Context, req CalleesRequest) (*CalleesResult, error) {
	return call[CalleesResult](ctx, g, ToolCallees, req)
}

// Reaches runs the engine's "reaches" tool on the graph g holds. req carries the
// tool's arguments; the result is its structuredContent, decoded. A query that
// the engine rejects returns a *ToolError.
func (g *Graph) Reaches(ctx context.Context, req ReachesRequest) (*ReachesResult, error) {
	return call[ReachesResult](ctx, g, ToolReaches, req)
}

// Paths runs the engine's "paths" tool on the graph g holds. req carries the
// tool's arguments; the result is its structuredContent, decoded. A query that
// the engine rejects returns a *ToolError.
func (g *Graph) Paths(ctx context.Context, req PathsRequest) (*PathsResult, error) {
	return call[PathsResult](ctx, g, ToolPaths, req)
}

// Unused runs the engine's "unused" tool on the graph g holds. req carries the
// tool's arguments; the result is its structuredContent, decoded. A query that
// the engine rejects returns a *ToolError.
func (g *Graph) Unused(ctx context.Context, req UnusedRequest) (*UnusedResult, error) {
	return call[UnusedResult](ctx, g, ToolUnused, req)
}

// Explain runs the engine's "explain" tool on the graph g holds. req carries the
// tool's arguments; the result is its structuredContent, decoded. A query that
// the engine rejects returns a *ToolError.
func (g *Graph) Explain(ctx context.Context, req ExplainRequest) (*ExplainResult, error) {
	return call[ExplainResult](ctx, g, ToolExplain, req)
}

// Search runs the engine's "search" tool on the graph g holds. req carries the
// tool's arguments; the result is its structuredContent, decoded. A query that
// the engine rejects returns a *ToolError.
func (g *Graph) Search(ctx context.Context, req SearchRequest) (*SearchResult, error) {
	return call[SearchResult](ctx, g, ToolSearch, req)
}

// Symbols runs the engine's "symbols" tool on the graph g holds. req carries the
// tool's arguments; the result is its structuredContent, decoded. A query that
// the engine rejects returns a *ToolError.
func (g *Graph) Symbols(ctx context.Context, req SymbolsRequest) (*SymbolsResult, error) {
	return call[SymbolsResult](ctx, g, ToolSymbols, req)
}

// FlowsTo runs the engine's "flows_to" tool on the graph g holds. req carries the
// tool's arguments; the result is its structuredContent, decoded. A query that
// the engine rejects returns a *ToolError.
func (g *Graph) FlowsTo(ctx context.Context, req FlowsToRequest) (*FlowsToResult, error) {
	return call[FlowsToResult](ctx, g, ToolFlowsTo, req)
}

// FlowsFrom runs the engine's "flows_from" tool on the graph g holds. req carries the
// tool's arguments; the result is its structuredContent, decoded. A query that
// the engine rejects returns a *ToolError.
func (g *Graph) FlowsFrom(ctx context.Context, req FlowsFromRequest) (*FlowsFromResult, error) {
	return call[FlowsFromResult](ctx, g, ToolFlowsFrom, req)
}

// Query runs the engine's "graph_query" tool on the graph g holds. req carries the
// tool's arguments; the result is its structuredContent, decoded. A query that
// the engine rejects returns a *ToolError.
func (g *Graph) Query(ctx context.Context, req GraphQueryRequest) (*GraphQueryResult, error) {
	return call[GraphQueryResult](ctx, g, ToolGraphQuery, req)
}
