// Code generated by schemagen from tools.json. DO NOT EDIT.

package cgx

import (
	"encoding/json"
	"fmt"
)

// ApproxDirection: The direction an answer can be wrong (GM-5 assertion-honesty). The fold of the
// per-reason directions: no reasons ⇒ [`Exact`](ApproxDirection::Exact).
type ApproxDirection string

const (
	ApproxDirectionExact     ApproxDirection = "exact"
	ApproxDirectionOver      ApproxDirection = "over"
	ApproxDirectionUnder     ApproxDirection = "under"
	ApproxDirectionOverUnder ApproxDirection = "over_under"
)

// ApproxReason: One machine-readable reason contributing to the [`ApproxDirection`]. `code` is
// a stable kebab-case token a CI consumer can match on; `detail` is a compact
// human phrase.
type ApproxReason struct {
	Code      string          `json:"code"`
	Detail    string          `json:"detail"`
	Direction ReasonDirection `json:"direction"`
}

// ApproximationContract: The per-answer approximation contract attached to every query answer.
type ApproximationContract struct {
	Direction ApproxDirection `json:"direction"`
	// The modeling boundary the whole contract (including `exact`) is relative
	// to. A property of *this answer*, not of the binary: every call-graph
	// answer carries [`MODELED_GRAPH`], while an answer derived from git
	// history supplies its own boundary via [`for_history`]. The field name is
	// historical — it is the answer's modeled domain, which is the call graph
	// only for the call-graph builders.
	ModeledGraph string         `json:"modeled_graph"`
	Reasons      []ApproxReason `json:"reasons"`
	// Present only for a *negative*/absence answer (A4).
	Scope *NegativeScope `json:"scope,omitempty"`
}

// CalleesRequest is the arguments of the "callees" tool.
type CalleesRequest struct {
	Confidence *Confidence `json:"confidence,omitempty"`
	Cursor     *string     `json:"cursor,omitempty"`
	// Default: 1.
	Depth         *int64         `json:"depth,omitempty"`
	EdgeCondition *EdgeCondition `json:"edge_condition,omitempty"`
	// Restrict traversal to these call-family edge kinds (default: all call edges)
	Kind []CallersRequestKind `json:"kind,omitempty"`
	// Drop call edges from an over-approximated candidate set larger than N targets (fan-out cap, orthogonal to confidence); excluded edges are reported in the approximation contract
	MaxCandidates *int64 `json:"max_candidates,omitempty"`
	// Default: 20.
	MaxResults *int64 `json:"max_results,omitempty"`
	// Qualified symbol name
	Symbol string `json:"symbol"`
}

// CalleesResult is the structuredContent of the "callees" tool.
type CalleesResult = NeighborOutput

// CallersRequest is the arguments of the "callers" tool.
type CallersRequest struct {
	Confidence *Confidence `json:"confidence,omitempty"`
	Cursor     *string     `json:"cursor,omitempty"`
	// Default: 1.
	Depth         *int64         `json:"depth,omitempty"`
	EdgeCondition *EdgeCondition `json:"edge_condition,omitempty"`
	// Restrict traversal to these call-family edge kinds (default: all call edges)
	Kind []CallersRequestKind `json:"kind,omitempty"`
	// Drop call edges from an over-approximated candidate set larger than N targets (fan-out cap, orthogonal to confidence); excluded edges are reported in the approximation contract
	MaxCandidates *int64 `json:"max_candidates,omitempty"`
	// Default: 20.
	MaxResults *int64 `json:"max_results,omitempty"`
	// Qualified symbol name
	Symbol string `json:"symbol"`
}

// CallersRequestKind is the value set of CallersRequest.kind.
type CallersRequestKind string

const (
	CallersRequestKindCalls         CallersRequestKind = "calls"
	CallersRequestKindCallsVirtual  CallersRequestKind = "calls_virtual"
	CallersRequestKindCallsClosure  CallersRequestKind = "calls_closure"
	CallersRequestKindCallsCallback CallersRequestKind = "calls_callback"
	CallersRequestKindCallsAsync    CallersRequestKind = "calls_async"
	CallersRequestKindCallsIndirect CallersRequestKind = "calls_indirect"
	CallersRequestKindSpawns        CallersRequestKind = "spawns"
)

// CallersResult is the structuredContent of the "callers" tool.
type CallersResult = NeighborOutput

// Confidence: How sure `cgx` is of an edge's target (GM-5.1).
//
// Discriminants ascend with certainty so the derived `Ord` answers "is this at
// least `probable`?" via `>=`, and so that "the weakest confidence of any
// contributing fact" (GM-1.3 node confidence) is a plain `min`.
type Confidence string

const (
	ConfidencePossible Confidence = "possible"
	ConfidenceProbable Confidence = "probable"
	ConfidenceCertain  Confidence = "certain"
)

// CouplingPair: One co-changed file pair. Every number here is a raw count of commits; the
// answer contains no derived, weighted, or fused quantity. `support` is
// `cochanges / commits_considered` and `confidence` is `cochanges / changes_a` —
// both inputs of both are emitted, so a caller that wants a ratio computes it
// and owns its definition.
type CouplingPair struct {
	// Commits in range in which `file_a` changed, with or without `file_b`.
	ChangesA uint32 `json:"changes_a"`
	// Commits in range in which `file_b` changed.
	ChangesB uint32 `json:"changes_b"`
	// Commits in range in which **both** paths changed.
	Cochanges uint32 `json:"cochanges"`
	// The smaller of the pair's two paths ordered on **path bytes**, rendered
	// lossily as UTF-8.
	//
	// The normalization happens on the raw bytes, which is what makes the answer
	// reproducible; the rendering happens afterwards and is *not* order-preserving
	// (an invalid byte becomes U+FFFD, which sorts below a valid U+FFFE even though
	// `0xFF > 0xEF` on bytes). So `file_a < file_b` holds on the path bytes and on
	// these strings whenever both paths are valid UTF-8, but not in general.
	FileA string `json:"file_a"`
	// The larger of the pair's two paths ordered on **path bytes**, rendered
	// lossily as UTF-8. See [`CouplingPair::file_a`] for why that is not
	// necessarily `file_a < file_b` as rendered.
	FileB string `json:"file_b"`
}

// CouplingReport: The answer envelope: what was asked, what was walked, the knobs, the pairs,
// and the approximation contract.
type CouplingReport struct {
	// Which direction this answer can be wrong, and why.
	Approximation ApproximationContract `json:"approximation"`
	// `base_rev` resolved to a 40-hex OID.
	BaseCommit string `json:"base_commit"`
	// The base revspec as the caller typed it.
	BaseRev string `json:"base_rev"`
	// Single-parent commits that contributed counts.
	CommitsConsidered uint32 `json:"commits_considered"`
	// Commits in range over `max_files_per_commit` (skipped).
	CommitsLargeExcluded uint32 `json:"commits_large_excluded"`
	// Commits in range with more than one parent (skipped).
	CommitsMergeExcluded uint32 `json:"commits_merge_excluded"`
	// Commits in range with no parent (skipped).
	CommitsRootExcluded uint32 `json:"commits_root_excluded"`
	// `head_rev` resolved to a 40-hex OID.
	HeadCommit string `json:"head_commit"`
	// The head revspec as the caller typed it.
	HeadRev string `json:"head_rev"`
	// Echo of [`CouplingOptions::limit`].
	Limit uint64 `json:"limit"`
	// Echo of [`CouplingOptions::max_files_per_commit`].
	MaxFilesPerCommit uint64 `json:"max_files_per_commit"`
	// Echo of [`CouplingOptions::min_cochanges`].
	MinCochanges uint32 `json:"min_cochanges"`
	// The reported pairs, sorted by `(Reverse(cochanges), file_a, file_b)`.
	Pairs []CouplingPair `json:"pairs"`
	// Pairs meeting `min_cochanges`, **before** `limit`.
	PairsTotal uint64 `json:"pairs_total"`
	// The repository is a shallow clone.
	ShallowRepository bool `json:"shallow_repository"`
	// The walk stopped early on an unreadable/missing object.
	TruncatedAtHistoryBoundary bool `json:"truncated_at_history_boundary"`
}

// CouplingRequest is the arguments of the "coupling" tool.
type CouplingRequest struct {
	// Range start, exclusive (rev/ref/SHA)
	Base string `json:"base"`
	// Range end, inclusive (rev/ref/SHA)
	Head string `json:"head"`
	// Default: 50.
	Limit *int64 `json:"limit,omitempty"`
	// Default: 50.
	MaxFilesPerCommit *int64 `json:"max_files_per_commit,omitempty"`
	// Default: 2.
	MinCochanges *int64 `json:"min_cochanges,omitempty"`
}

// CouplingResult is the structuredContent of the "coupling" tool.
type CouplingResult = CouplingReport

// CqlCell: One cell of a `graph_query` table row, untagged. The JSON value alone does
// not always identify the variant: `Int` and `Float` are both JSON numbers
// (every integer also matches `Float`), and a bound path renders as an array
// of FQN strings, the same JSON as a `List` of `Str`. Decode cells lazily (Go:
// `json.RawMessage`, numbers via `json.Number`) and use the query's own
// `RETURN` clause to know which column is a path.
//
// CqlCell is a union the generator does not model (8 variants); decode it as needed.
type CqlCell = json.RawMessage

// CqlEdge: A bound relationship in a `graph_query` cell.
type CqlEdge struct {
	// Edge condition.
	Condition EdgeCondition `json:"condition"`
	// Edge confidence.
	Confidence Confidence `json:"confidence"`
	// Edge kind.
	Kind EdgeKind `json:"kind"`
}

// CqlNode: A bound node in a `graph_query` cell.
type CqlNode struct {
	// Repo-relative definition file.
	File string `json:"file"`
	// Fully qualified symbol name (opaque).
	FQN string `json:"fqn"`
	// Symbol kind.
	Kind SymbolKind `json:"kind"`
	// 1-based definition line.
	Line uint32 `json:"line"`
}

// EdgeBreakdown: Incident edges in one direction, tallied three ways.
type EdgeBreakdown struct {
	// Count per edge condition token.
	ByCondition map[string]uint64 `json:"by_condition"`
	// Count per confidence token.
	ByConfidence map[string]uint64 `json:"by_confidence"`
	// Count per edge family (`calls`, `derives_from`).
	ByFamily map[string]uint64 `json:"by_family"`
	// Total edges in this direction.
	Total uint64 `json:"total"`
}

// EdgeCondition: The runtime condition under which a call edge is taken (GM-3).
//
// The five-value set is frozen. The discriminant values are assigned in
// ascending precedence order so that [`EdgeCondition::max`] is a plain integer
// comparison and the derived `Ord` matches the ADR-03 precedence total order.
type EdgeCondition string

const (
	EdgeConditionAlways      EdgeCondition = "always"
	EdgeConditionConditional EdgeCondition = "conditional"
	EdgeConditionLoop        EdgeCondition = "loop"
	EdgeConditionException   EdgeCondition = "exception"
	EdgeConditionPanic       EdgeCondition = "panic"
)

// EdgeDirection: Which way an `explain` edge points relative to the explained symbol.
type EdgeDirection string

const (
	EdgeDirectionIncoming EdgeDirection = "incoming"
	EdgeDirectionOutgoing EdgeDirection = "outgoing"
)

// EdgeKind: Edge kinds (GM-2.1 call edges, GM-2.2 structural/dataflow, GM-9 `spawns`).
//
// `spawns` is an edge *kind*, orthogonal to the edge-condition label set
// (GM-9.1); a spawn inside a `catch` is `Spawns` with condition `Exception`.
type EdgeKind string

const (
	EdgeKindCalls         EdgeKind = "calls"
	EdgeKindCallsVirtual  EdgeKind = "calls-virtual"
	EdgeKindCallsClosure  EdgeKind = "calls-closure"
	EdgeKindCallsCallback EdgeKind = "calls-callback"
	EdgeKindCallsAsync    EdgeKind = "calls-async"
	EdgeKindCallsIndirect EdgeKind = "calls-indirect"
	EdgeKindSpawns        EdgeKind = "spawns"
	EdgeKindContains      EdgeKind = "contains"
	EdgeKindImports       EdgeKind = "imports"
	EdgeKindDerivesFrom   EdgeKind = "derives-from"
	EdgeKindOverrides     EdgeKind = "overrides"
	EdgeKindImplements    EdgeKind = "implements"
	EdgeKindInherits      EdgeKind = "inherits"
	EdgeKindReferences    EdgeKind = "references"
	EdgeKindInstantiates  EdgeKind = "instantiates"
	EdgeKindThrows        EdgeKind = "throws"
	EdgeKindCatches       EdgeKind = "catches"
	EdgeKindReadsField    EdgeKind = "reads-field"
	EdgeKindWritesField   EdgeKind = "writes-field"
)

// ExplainEdgeRow: One edge incident on the explained symbol, with its provenance.
type ExplainEdgeRow struct {
	// Edge condition.
	Condition EdgeCondition `json:"condition"`
	// Edge confidence.
	Confidence Confidence `json:"confidence"`
	// Incoming (`peer` calls the symbol) or outgoing (the symbol calls `peer`).
	Direction EdgeDirection `json:"direction"`
	// Fully qualified name of the other endpoint (opaque).
	Peer string `json:"peer"`
	// Repo-relative definition file of `peer`.
	PeerFile string `json:"peer_file"`
	// 1-based definition line of `peer`.
	PeerLine uint32 `json:"peer_line"`
	// External resolution source, when the edge was not resolved in-repo.
	ResolutionSource *string `json:"resolution_source"`
	// The resolver rule that produced the edge.
	Rule string `json:"rule"`
	// Call site, when recorded.
	Site *SiteRef `json:"site"`
	// Resolution tier that produced the edge.
	Tier Tier `json:"tier"`
}

// ExplainOutput: `explain`. Carries no `approximation`: it performs no traversal.
type ExplainOutput struct {
	CalleesCount uint64 `json:"callees_count"`
	CallersCount uint64 `json:"callers_count"`
	// The working-tree overlay was active and changed the base graph.
	Dirty bool `json:"dirty"`
	// Paths the overlay fed the indexer differently from `HEAD`.
	DirtyFilesAnalyzed uint64           `json:"dirty_files_analyzed"`
	Edges              []ExplainEdgeRow `json:"edges"`
	// Repo-relative definition file.
	File string `json:"file"`
	// Which tree the answer was computed over.
	Freshness FreshnessEnvelope `json:"freshness"`
	// Cache key of the graph the answer was computed over: a 7-character tree
	// OID, or `<oid>+dirty.<digest>` when the working-tree overlay changed it.
	GraphVersion string `json:"graph_version"`
	// Symbol kind.
	Kind SymbolKind `json:"kind"`
	// 1-based definition line.
	Line uint32 `json:"line"`
	// The resolved fully qualified name (opaque).
	Symbol string `json:"symbol"`
}

// ExplainRequest is the arguments of the "explain" tool.
type ExplainRequest struct {
	Symbol string `json:"symbol"`
}

// ExplainResult is the structuredContent of the "explain" tool.
type ExplainResult = ExplainOutput

// FlowsFromRequest is the arguments of the "flows_from" tool.
type FlowsFromRequest struct {
	Confidence *Confidence `json:"confidence,omitempty"`
	Cursor     *string     `json:"cursor,omitempty"`
	// Default: 2.
	Depth *int64 `json:"depth,omitempty"`
	// Default: 20.
	MaxResults *int64 `json:"max_results,omitempty"`
	// Qualified symbol name
	Symbol string `json:"symbol"`
}

// FlowsFromResult is the structuredContent of the "flows_from" tool.
type FlowsFromResult = NeighborOutput

// FlowsToRequest is the arguments of the "flows_to" tool.
type FlowsToRequest struct {
	Confidence *Confidence `json:"confidence,omitempty"`
	Cursor     *string     `json:"cursor,omitempty"`
	// Default: 2.
	Depth *int64 `json:"depth,omitempty"`
	// Default: 20.
	MaxResults *int64 `json:"max_results,omitempty"`
	// Qualified symbol name
	Symbol string `json:"symbol"`
}

// FlowsToResult is the structuredContent of the "flows_to" tool.
type FlowsToResult = NeighborOutput

// FreshnessEnvelope: How far the indexed state is from the working state (no wall-clock: this is
// divergence, not age).
//
// Construct with [`FreshnessEnvelope::new`] — [`stale`](Self::stale) and
// [`matches_head`](Self::matches_head) are *derived* there and are never sourced
// independently, so the one-glance boolean cannot drift from the facts under it.
type FreshnessEnvelope struct {
	// How many working-tree files diverge from
	// [`dirty_files_base`](Self::dirty_files_base) (content differs, or the file
	// was added/removed). `null` when the surface did not inspect the working
	// tree; `0` when it did and found none.
	//
	// Ignored paths are excluded and nested repositories (submodules) are not
	// descended into, matching what the index itself covers. The exclude rules
	// git applies include machine-global ones — `$GIT_DIR/info/exclude`,
	// `core.excludesFile`, `$XDG_CONFIG_HOME/git/ignore` — which are not part of
	// the tree, so two checkouts identical byte-for-byte can report different
	// counts on differently configured machines. Repeated runs on one machine are
	// byte-stable (AR-10); the count is not portable across them.
	DirtyFiles *uint64 `json:"dirty_files"`
	// The tree [`dirty_files`](Self::dirty_files) was measured against — the
	// base of that count, and `null` exactly when the count is.
	//
	// It is **not** always [`indexed_tree`](Self::indexed_tree), which is why it
	// is reported rather than inferred: the CLI measures divergence from the tree
	// its index pointer names, while a working-directory MCP query measures it
	// from `HEAD`'s tree even though the graph it answered over is a synthetic
	// `workdir:` key that names no tree at all. Both are the right base for their
	// own question; a count whose base a reader has to guess is not a
	// self-describing account of an answer's limits.
	DirtyFilesBase *string `json:"dirty_files_base"`
	// The tree OID of the current `HEAD` commit; `null` when no `HEAD` tree could
	// be resolved (not a git repository, or no commits yet).
	HeadTree *string `json:"head_tree"`
	// The Layer-2 key of the graph this answer was computed over: a git tree OID
	// for an indexed committed tree, or a synthetic `workdir:<digest>` key when
	// the graph came from a working-directory index whose content is not some
	// committed tree's. `null` only where the surface could not recover its own
	// graph key.
	IndexedTree *string `json:"indexed_tree"`
	// Whether [`indexed_tree`](Self::indexed_tree) is the current `HEAD` tree.
	// `false` means the index is pinned to, or lagging behind, a different commit.
	// `null` when either tree is unknown, or when the surface could not establish
	// the relation (see [`indeterminate_head`](Self::indeterminate_head)) — never
	// `false`, which would assert a divergence nobody established, and never
	// `true`, which would be a clean bill nobody established.
	MatchesHead *bool `json:"matches_head"`
	// The one-glance signal, **derived** from the fields above: `true` iff a
	// divergence was actually established — the indexed tree is known not to be
	// `HEAD`'s, or at least one working-tree file is known to differ. `false` is
	// therefore "no divergence within what this envelope reports", not a claim
	// about what was never looked at; the `null`s above say which is which.
	Stale bool `json:"stale"`
}

// GraphQueryOutput: `graph_query`: the paths channel (`paths` present) or the table channel
// (`rows` present).
//
// Exactly one of its fields is set: one of GraphQueryPathsOutput, GraphQueryTableOutput.
type GraphQueryOutput struct {
	GraphQueryPathsOutput *GraphQueryPathsOutput
	GraphQueryTableOutput *GraphQueryTableOutput
}

// UnmarshalJSON picks the variant by the presence of its distinguishing property.
func (u *GraphQueryOutput) UnmarshalJSON(b []byte) error {
	var keys map[string]json.RawMessage
	if err := json.Unmarshal(b, &keys); err != nil {
		return err
	}
	*u = GraphQueryOutput{}
	if _, ok := keys["paths"]; ok {
		u.GraphQueryPathsOutput = new(GraphQueryPathsOutput)
		return json.Unmarshal(b, u.GraphQueryPathsOutput)
	}
	if _, ok := keys["rows"]; ok {
		u.GraphQueryTableOutput = new(GraphQueryTableOutput)
		return json.Unmarshal(b, u.GraphQueryTableOutput)
	}
	return fmt.Errorf("cgx: GraphQueryOutput matches none of its variants")
}

// MarshalJSON encodes the set variant.
func (u GraphQueryOutput) MarshalJSON() ([]byte, error) {
	switch {
	case u.GraphQueryPathsOutput != nil:
		return json.Marshal(u.GraphQueryPathsOutput)
	case u.GraphQueryTableOutput != nil:
		return json.Marshal(u.GraphQueryTableOutput)
	}
	return []byte("null"), nil
}

// GraphQueryPathsOutput: `graph_query` whose `RETURN` binds a path: the `paths`-tool row shape. Told
// apart from [`GraphQueryTableOutput`] by the `paths` key.
type GraphQueryPathsOutput struct {
	Approximation ApproximationContract `json:"approximation"`
	Columns       []string              `json:"columns"`
	// Opaque cursor for the next page; `null` exactly when `has_more` is false.
	Cursor *string `json:"cursor"`
	// The working-tree overlay was active and changed the base graph.
	Dirty bool `json:"dirty"`
	// Paths the overlay fed the indexer differently from `HEAD`.
	DirtyFilesAnalyzed uint64 `json:"dirty_files_analyzed"`
	// Which tree the answer was computed over.
	Freshness FreshnessEnvelope `json:"freshness"`
	// Cache key of the graph the answer was computed over: a 7-character tree
	// OID, or `<oid>+dirty.<digest>` when the working-tree overlay changed it.
	GraphVersion string `json:"graph_version"`
	// More results exist beyond this page.
	HasMore bool      `json:"has_more"`
	Paths   []PathRow `json:"paths"`
	// Size of the full result set, across all pages.
	TotalMatched     uint64            `json:"total_matched"`
	Truncated        bool              `json:"truncated"`
	TruncationReason *TruncationReason `json:"truncation_reason"`
}

// GraphQueryRequest is the arguments of the "graph_query" tool.
type GraphQueryRequest struct {
	Cursor *string `json:"cursor,omitempty"`
	// Default: 20.
	MaxResults *int64 `json:"max_results,omitempty"`
	// Cypher-subset query expression
	Query string `json:"query"`
}

// GraphQueryResult is the structuredContent of the "graph_query" tool.
type GraphQueryResult = GraphQueryOutput

// GraphQueryTableOutput: `graph_query` with a tabular `RETURN`. Told apart from
// [`GraphQueryPathsOutput`] by the `rows` key.
type GraphQueryTableOutput struct {
	Approximation ApproximationContract `json:"approximation"`
	Columns       []string              `json:"columns"`
	// Opaque cursor for the next page; `null` exactly when `has_more` is false.
	Cursor *string `json:"cursor"`
	// The working-tree overlay was active and changed the base graph.
	Dirty bool `json:"dirty"`
	// Paths the overlay fed the indexer differently from `HEAD`.
	DirtyFilesAnalyzed uint64 `json:"dirty_files_analyzed"`
	// Which tree the answer was computed over.
	Freshness FreshnessEnvelope `json:"freshness"`
	// Cache key of the graph the answer was computed over: a 7-character tree
	// OID, or `<oid>+dirty.<digest>` when the working-tree overlay changed it.
	GraphVersion string `json:"graph_version"`
	// More results exist beyond this page.
	HasMore bool `json:"has_more"`
	// One array per row, index-parallel to `columns`.
	Rows [][]CqlCell `json:"rows"`
	// Size of the full result set, across all pages.
	TotalMatched     uint64            `json:"total_matched"`
	Truncated        bool              `json:"truncated"`
	TruncationReason *TruncationReason `json:"truncation_reason"`
}

// ImpactedRow: One `impacted_tests` row: a test entrypoint, how it was reached, and which
// changed symbol it reaches.
type ImpactedRow struct {
	// Confidence of the edge that reached this symbol.
	Confidence Confidence `json:"confidence"`
	// Hop distance from the anchor symbol.
	Depth uint32 `json:"depth"`
	// Condition of the edge that reached this symbol.
	EdgeCondition EdgeCondition `json:"edge_condition"`
	// The discovery path crossed an exceptional-class edge.
	ExceptionTransient bool `json:"exception_transient"`
	// Repo-relative definition file.
	File string `json:"file"`
	// 1-based definition line.
	Line uint32 `json:"line"`
	// Weakest edge confidence along the discovery path.
	MinConfidenceOnPath Confidence `json:"min_confidence_on_path"`
	// Fully qualified symbol name (opaque).
	Name string `json:"name"`
	// Fully qualified name of the changed symbol this test reaches.
	ReachedChange *string `json:"reached_change"`
	// The path crossed a closure-containment lift (containment is not
	// invocation, so the row is an over-approximation).
	ViaContainmentLift bool `json:"via_containment_lift"`
}

// ImpactedTestsOutput: `impacted_tests`. Compares two graphs, so it reports both graph keys rather
// than a single `graph_version`.
type ImpactedTestsOutput struct {
	Approximation ApproximationContract `json:"approximation"`
	// Graph key of the base side: a tree OID or `workdir:<digest>`.
	BaseGraphKey string `json:"base_graph_key"`
	// What the base side resolved to: a commit hex, or `workdir`.
	BaseRef string `json:"base_ref"`
	// Number of changed symbols the walk was seeded with.
	ChangedSymbols uint64 `json:"changed_symbols"`
	// Opaque cursor for the next page; `null` exactly when `has_more` is false.
	Cursor *string `json:"cursor"`
	// No changed symbol is in a language whose tests cgx identifies: an empty
	// result means "not analysed", not "no tests affected".
	Degenerate       bool    `json:"degenerate"`
	DegenerateReason *string `json:"degenerate_reason"`
	// The head side is the working directory.
	Dirty bool `json:"dirty"`
	// Files whose content differs between the two sides.
	DirtyFilesAnalyzed uint64            `json:"dirty_files_analyzed"`
	Freshness          FreshnessEnvelope `json:"freshness"`
	// More results exist beyond this page.
	HasMore bool `json:"has_more"`
	// Graph key of the head side: a tree OID or `workdir:<digest>`.
	HeadGraphKey string `json:"head_graph_key"`
	// What the head side resolved to: a commit hex, or `workdir`.
	HeadRef string        `json:"head_ref"`
	Results []ImpactedRow `json:"results"`
	// Size of the full result set, across all pages.
	TotalMatched uint64 `json:"total_matched"`
}

// ImpactedTestsRequest is the arguments of the "impacted_tests" tool.
type ImpactedTestsRequest struct {
	// Base git ref. Omit to compare the working tree against HEAD.
	Base       *string     `json:"base,omitempty"`
	Confidence *Confidence `json:"confidence,omitempty"`
	Cursor     *string     `json:"cursor,omitempty"`
	// Max traversal depth from each changed symbol; omit for unbounded
	Depth *int64 `json:"depth,omitempty"`
	// Head git ref (default: HEAD). Used only when `base` is given and `include_dirty` is false.
	Head *string `json:"head,omitempty"`
	// Default: 20.
	MaxResults *int64 `json:"max_results,omitempty"`
	// Compare against the merge-base of base and head rather than the base ref's tip Default: true.
	MergeBase *bool `json:"merge_base,omitempty"`
}

// ImpactedTestsResult is the structuredContent of the "impacted_tests" tool.
type ImpactedTestsResult = ImpactedTestsOutput

// NegativeScope: The scope of a *negative* answer (A4): what the search covered, so a consumer
// can gate on the negative claim instead of trusting a bare "no". The
// invalidators ("what could make this negative wrong") are the `under`-direction
// entries in the contract's `reasons`.
type NegativeScope struct {
	// The minimum edge confidence the search required (edges below this were not
	// followed). `possible` means "every edge".
	ConfidenceFloor Confidence `json:"confidence_floor"`
	// The maximum hop depth searched; `null` = unbounded.
	MaxDepth *uint32 `json:"max_depth"`
	// The edge kinds the search followed. The call family is spelled out so the
	// claim is self-describing.
	SearchedEdgeKinds []EdgeKind `json:"searched_edge_kinds"`
}

// NeighborOutput: `callers`, `callees`, `flows_to`, `flows_from`.
type NeighborOutput struct {
	Approximation ApproximationContract `json:"approximation"`
	// Opaque cursor for the next page; `null` exactly when `has_more` is false.
	Cursor *string `json:"cursor"`
	// The working-tree overlay was active and changed the base graph.
	Dirty bool `json:"dirty"`
	// Paths the overlay fed the indexer differently from `HEAD`.
	DirtyFilesAnalyzed uint64 `json:"dirty_files_analyzed"`
	// Which tree the answer was computed over.
	Freshness FreshnessEnvelope `json:"freshness"`
	// Cache key of the graph the answer was computed over: a 7-character tree
	// OID, or `<oid>+dirty.<digest>` when the working-tree overlay changed it.
	GraphVersion string `json:"graph_version"`
	// More results exist beyond this page.
	HasMore bool          `json:"has_more"`
	Results []NeighborRow `json:"results"`
	// The `symbol` argument as received (not the resolved FQN).
	Symbol string `json:"symbol"`
	// Size of the full result set, across all pages.
	TotalMatched uint64 `json:"total_matched"`
}

// NeighborRow: One symbol reached by a neighbor walk (`callers`, `callees`, `reaches` without
// `to`, `flows_to`, `flows_from`).
type NeighborRow struct {
	// Confidence of the edge that reached this symbol.
	Confidence Confidence `json:"confidence"`
	// Hop distance from the anchor symbol.
	Depth uint32 `json:"depth"`
	// Condition of the edge that reached this symbol.
	EdgeCondition EdgeCondition `json:"edge_condition"`
	// The discovery path crossed an exceptional-class edge.
	ExceptionTransient bool `json:"exception_transient"`
	// Repo-relative definition file.
	File string `json:"file"`
	// 1-based definition line.
	Line uint32 `json:"line"`
	// Weakest edge confidence along the discovery path.
	MinConfidenceOnPath Confidence `json:"min_confidence_on_path"`
	// Fully qualified symbol name (opaque).
	Name string `json:"name"`
}

// PathRow: One call path.
type PathRow struct {
	// Some edge on the path is exceptional-class.
	CrossesExceptional bool `json:"crosses_exceptional"`
	// Number of edges (`steps.len() - 1`).
	Hops uint64 `json:"hops"`
	// Weakest edge confidence on the path.
	MinConfidence Confidence `json:"min_confidence"`
	// The path's nodes, in call order.
	Steps []PathStepRow `json:"steps"`
}

// PathStepRow: One node of a call path. The first step has no incoming edge, so its
// `edge_condition` and `confidence` are `null`.
type PathStepRow struct {
	// Confidence of the edge into this step.
	Confidence *Confidence `json:"confidence"`
	// Condition of the edge into this step.
	EdgeCondition *EdgeCondition `json:"edge_condition"`
	// The path up to this step has crossed an exceptional-class edge.
	ExceptionTransient bool `json:"exception_transient"`
	// Repo-relative definition file.
	File string `json:"file"`
	// 1-based definition line.
	Line uint32 `json:"line"`
	// Fully qualified symbol name (opaque).
	Name string `json:"name"`
}

// PathsOutput: `paths`.
type PathsOutput struct {
	Approximation ApproximationContract `json:"approximation"`
	// Opaque cursor for the next page; `null` exactly when `has_more` is false.
	Cursor *string `json:"cursor"`
	// The working-tree overlay was active and changed the base graph.
	Dirty bool `json:"dirty"`
	// Paths the overlay fed the indexer differently from `HEAD`.
	DirtyFilesAnalyzed uint64 `json:"dirty_files_analyzed"`
	// Which tree the answer was computed over.
	Freshness FreshnessEnvelope `json:"freshness"`
	// The `from` argument as received.
	From string `json:"from"`
	// Cache key of the graph the answer was computed over: a 7-character tree
	// OID, or `<oid>+dirty.<digest>` when the working-tree overlay changed it.
	GraphVersion string `json:"graph_version"`
	// More results exist beyond this page.
	HasMore bool      `json:"has_more"`
	Paths   []PathRow `json:"paths"`
	// The `to` argument as received.
	To string `json:"to"`
	// Size of the full result set, across all pages.
	TotalMatched uint64 `json:"total_matched"`
	// A traversal bound cut the enumeration short.
	Truncated bool `json:"truncated"`
	// Which bound; `null` when the enumeration was complete.
	TruncationReason *TruncationReason `json:"truncation_reason"`
}

// PathsRequest is the arguments of the "paths" tool.
type PathsRequest struct {
	Confidence           *Confidence    `json:"confidence,omitempty"`
	Cursor               *string        `json:"cursor,omitempty"`
	ExcludeEdgeCondition *EdgeCondition `json:"exclude_edge_condition,omitempty"`
	From                 string         `json:"from"`
	// Drop call edges from an over-approximated candidate set larger than N targets (fan-out cap, orthogonal to confidence); excluded edges are reported in the approximation contract
	MaxCandidates *int64 `json:"max_candidates,omitempty"`
	// Default: 10.
	MaxDepth *int64 `json:"max_depth,omitempty"`
	// Default: 10.
	MaxResults        *int64         `json:"max_results,omitempty"`
	OnlyEdgeCondition *EdgeCondition `json:"only_edge_condition,omitempty"`
	To                string         `json:"to"`
}

// PathsResult is the structuredContent of the "paths" tool.
type PathsResult = PathsOutput

// ReachesOutput: `reaches`: the pair form when `to` was given (`reachable` present), the set
// form otherwise (`results` present).
//
// Exactly one of its fields is set: one of ReachesPairOutput, ReachesSetOutput.
type ReachesOutput struct {
	ReachesPairOutput *ReachesPairOutput
	ReachesSetOutput  *ReachesSetOutput
}

// UnmarshalJSON picks the variant by the presence of its distinguishing property.
func (u *ReachesOutput) UnmarshalJSON(b []byte) error {
	var keys map[string]json.RawMessage
	if err := json.Unmarshal(b, &keys); err != nil {
		return err
	}
	*u = ReachesOutput{}
	if _, ok := keys["reachable"]; ok {
		u.ReachesPairOutput = new(ReachesPairOutput)
		return json.Unmarshal(b, u.ReachesPairOutput)
	}
	if _, ok := keys["cursor"]; ok {
		u.ReachesSetOutput = new(ReachesSetOutput)
		return json.Unmarshal(b, u.ReachesSetOutput)
	}
	return fmt.Errorf("cgx: ReachesOutput matches none of its variants")
}

// MarshalJSON encodes the set variant.
func (u ReachesOutput) MarshalJSON() ([]byte, error) {
	switch {
	case u.ReachesPairOutput != nil:
		return json.Marshal(u.ReachesPairOutput)
	case u.ReachesSetOutput != nil:
		return json.Marshal(u.ReachesSetOutput)
	}
	return []byte("null"), nil
}

// ReachesPairOutput: `reaches` with `to`: one reachability verdict and its witness. Told apart
// from [`ReachesSetOutput`] by the `reachable` key.
type ReachesPairOutput struct {
	Approximation ApproximationContract `json:"approximation"`
	// The working-tree overlay was active and changed the base graph.
	Dirty bool `json:"dirty"`
	// Paths the overlay fed the indexer differently from `HEAD`.
	DirtyFilesAnalyzed uint64 `json:"dirty_files_analyzed"`
	// Which tree the answer was computed over.
	Freshness FreshnessEnvelope `json:"freshness"`
	// The `from` argument as received.
	From string `json:"from"`
	// Cache key of the graph the answer was computed over: a 7-character tree
	// OID, or `<oid>+dirty.<digest>` when the working-tree overlay changed it.
	GraphVersion string `json:"graph_version"`
	Reachable    bool   `json:"reachable"`
	// The `to` argument as received.
	To string `json:"to"`
	// A shortest witness path; `null` when not reachable.
	Witness *PathRow `json:"witness"`
}

// ReachesRequest is the arguments of the "reaches" tool.
type ReachesRequest struct {
	Confidence *Confidence `json:"confidence,omitempty"`
	Cursor     *string     `json:"cursor,omitempty"`
	// Max traversal depth (from→* form) Default: 2.
	Depth *int64 `json:"depth,omitempty"`
	// Source symbol (qualified name)
	From string `json:"from"`
	// Drop call edges from an over-approximated candidate set larger than N targets (fan-out cap, orthogonal to confidence); excluded edges are reported in the approximation contract
	MaxCandidates *int64 `json:"max_candidates,omitempty"`
	// Default: 20.
	MaxResults *int64 `json:"max_results,omitempty"`
	// Optional target symbol; omit for the from→* reachable set
	To *string `json:"to,omitempty"`
}

// ReachesResult is the structuredContent of the "reaches" tool.
type ReachesResult = ReachesOutput

// ReachesSetOutput: `reaches` without `to`: every symbol `from` reaches. Told apart from
// [`ReachesPairOutput`] by the `results` key.
type ReachesSetOutput struct {
	Approximation ApproximationContract `json:"approximation"`
	// Opaque cursor for the next page; `null` exactly when `has_more` is false.
	Cursor *string `json:"cursor"`
	// The working-tree overlay was active and changed the base graph.
	Dirty bool `json:"dirty"`
	// Paths the overlay fed the indexer differently from `HEAD`.
	DirtyFilesAnalyzed uint64 `json:"dirty_files_analyzed"`
	// Which tree the answer was computed over.
	Freshness FreshnessEnvelope `json:"freshness"`
	// The `from` argument as received.
	From string `json:"from"`
	// Cache key of the graph the answer was computed over: a 7-character tree
	// OID, or `<oid>+dirty.<digest>` when the working-tree overlay changed it.
	GraphVersion string `json:"graph_version"`
	// More results exist beyond this page.
	HasMore bool          `json:"has_more"`
	Results []NeighborRow `json:"results"`
	// Size of the full result set, across all pages.
	TotalMatched uint64 `json:"total_matched"`
}

// ReasonDirection: Which way a single [`ApproxReason`] pushes the answer.
type ReasonDirection string

const (
	ReasonDirectionOver  ReasonDirection = "over"
	ReasonDirectionUnder ReasonDirection = "under"
)

// SearchOutput: `search`. Carries no `approximation`: it is a node-table scan.
type SearchOutput struct {
	// Opaque cursor for the next page; `null` exactly when `has_more` is false.
	Cursor *string `json:"cursor"`
	// The working-tree overlay was active and changed the base graph.
	Dirty bool `json:"dirty"`
	// Paths the overlay fed the indexer differently from `HEAD`.
	DirtyFilesAnalyzed uint64 `json:"dirty_files_analyzed"`
	// Which tree the answer was computed over.
	Freshness FreshnessEnvelope `json:"freshness"`
	// Cache key of the graph the answer was computed over: a 7-character tree
	// OID, or `<oid>+dirty.<digest>` when the working-tree overlay changed it.
	GraphVersion string `json:"graph_version"`
	// More results exist beyond this page.
	HasMore bool           `json:"has_more"`
	Results []SymbolHitRow `json:"results"`
	// Size of the full result set, across all pages.
	TotalMatched uint64 `json:"total_matched"`
}

// SearchRequest is the arguments of the "search" tool.
type SearchRequest struct {
	// List every symbol (mutually exclusive with `pattern`) Default: false.
	All    *bool   `json:"all,omitempty"`
	Cursor *string `json:"cursor,omitempty"`
	// Default: "all".
	Kind *SearchRequestKind `json:"kind,omitempty"`
	// Default: 20.
	MaxResults *int64 `json:"max_results,omitempty"`
	// Name predicate over the whole FQN (case-insensitive substring, or regex when `regex` is true)
	Pattern *string `json:"pattern,omitempty"`
	// Treat `pattern` as an unanchored regex Default: false.
	Regex *bool `json:"regex,omitempty"`
}

// SearchRequestKind is the value set of SearchRequest.kind.
type SearchRequestKind string

const (
	SearchRequestKindFunction SearchRequestKind = "function"
	SearchRequestKindMethod   SearchRequestKind = "method"
	SearchRequestKindField    SearchRequestKind = "field"
	SearchRequestKindType     SearchRequestKind = "type"
	SearchRequestKindModule   SearchRequestKind = "module"
	SearchRequestKindAll      SearchRequestKind = "all"
)

// SearchResult is the structuredContent of the "search" tool.
type SearchResult = SearchOutput

// SiteRef: A source location.
type SiteRef struct {
	// Repo-relative file.
	File string `json:"file"`
	// 1-based line.
	Line uint32 `json:"line"`
}

// SymbolHitRow: One `search` hit.
type SymbolHitRow struct {
	// Repo-relative definition file.
	File string `json:"file"`
	// Fully qualified symbol name (opaque).
	FQN string `json:"fqn"`
	// Symbol kind.
	Kind SymbolKind `json:"kind"`
	// 1-based definition line.
	Line uint32 `json:"line"`
}

// SymbolKind: Symbol kinds (GM-1.1). Every named program entity is a symbol.
type SymbolKind string

const (
	SymbolKindFunction   SymbolKind = "function"
	SymbolKindMethod     SymbolKind = "method"
	SymbolKindType       SymbolKind = "type"
	SymbolKindField      SymbolKind = "field"
	SymbolKindVariable   SymbolKind = "variable"
	SymbolKindModule     SymbolKind = "module"
	SymbolKindConstant   SymbolKind = "constant"
	SymbolKindMacro      SymbolKind = "macro"
	SymbolKindLambda     SymbolKind = "lambda"
	SymbolKindEntrypoint SymbolKind = "entrypoint"
)

// SymbolRankRow: One `symbols` row: a symbol and its reference counts.
type SymbolRankRow struct {
	// Repo-relative definition file.
	File string `json:"file"`
	// Fully qualified symbol name (opaque).
	FQN string `json:"fqn"`
	// Incoming edge count.
	InDegree uint64 `json:"in_degree"`
	// Incoming edges by family, condition and confidence.
	Inbound EdgeBreakdown `json:"inbound"`
	// Symbol kind.
	Kind SymbolKind `json:"kind"`
	// 1-based definition line.
	Line uint32 `json:"line"`
	// Outgoing edge count.
	OutDegree uint64 `json:"out_degree"`
	// Outgoing edges by family, condition and confidence.
	Outbound EdgeBreakdown `json:"outbound"`
}

// SymbolsOutput: `symbols`. Carries no `approximation`: it is a degree aggregate.
type SymbolsOutput struct {
	// Opaque cursor for the next page; `null` exactly when `has_more` is false.
	Cursor *string `json:"cursor"`
	// The working-tree overlay was active and changed the base graph.
	Dirty bool `json:"dirty"`
	// Paths the overlay fed the indexer differently from `HEAD`.
	DirtyFilesAnalyzed uint64 `json:"dirty_files_analyzed"`
	// Which tree the answer was computed over.
	Freshness FreshnessEnvelope `json:"freshness"`
	// Cache key of the graph the answer was computed over: a 7-character tree
	// OID, or `<oid>+dirty.<digest>` when the working-tree overlay changed it.
	GraphVersion string `json:"graph_version"`
	// More results exist beyond this page.
	HasMore bool            `json:"has_more"`
	Results []SymbolRankRow `json:"results"`
	// Size of the full result set, across all pages.
	TotalMatched uint64 `json:"total_matched"`
}

// SymbolsRequest is the arguments of the "symbols" tool.
type SymbolsRequest struct {
	Cursor *string `json:"cursor,omitempty"`
	// Default: "all".
	Kind *SearchRequestKind `json:"kind,omitempty"`
	// Default: 20.
	MaxResults *int64 `json:"max_results,omitempty"`
	// Default: "total".
	Rank *SymbolsRequestRank `json:"rank,omitempty"`
}

// SymbolsRequestRank is the value set of SymbolsRequest.rank.
type SymbolsRequestRank string

const (
	SymbolsRequestRankTotal    SymbolsRequestRank = "total"
	SymbolsRequestRankInbound  SymbolsRequestRank = "inbound"
	SymbolsRequestRankOutbound SymbolsRequestRank = "outbound"
)

// SymbolsResult is the structuredContent of the "symbols" tool.
type SymbolsResult = SymbolsOutput

// Tier: The resolution tier that produced an edge (GM-5.2). Recorded in provenance.
//
// The ladder is strictly narrowing; each tier emits a confidence band. Phase 1
// ships tiers 0–1; tiers 2–4 are reserved so the schema does not change when
// SCIP/CHA/points-to enrichment lands.
type Tier string

const (
	TierNameSyntactic Tier = "name_syntactic"
	TierScopeGraph    Tier = "scope_graph"
	TierSCIP          Tier = "scip"
	TierCHARTA        Tier = "cha_rta"
	TierPointsTo      Tier = "points_to"
)

// TruncationReason: Why a `paths` enumeration stopped before exhausting the full simple-path set.
// `None` (absent) means the enumeration was complete; a value names which bound
// it hit. Mirrors the [`cgx_core::CutMarker`] honesty idiom: a budget cutoff is a
// surfaced fact, never a silent drop and never an error.
type TruncationReason string

const (
	TruncationReasonStepBudget TruncationReason = "step-budget"
	TruncationReasonPathCap    TruncationReason = "path-cap"
)

// UnusedOutput: `unused`.
type UnusedOutput struct {
	Approximation ApproximationContract `json:"approximation"`
	// Opaque cursor for the next page; `null` exactly when `has_more` is false.
	Cursor *string `json:"cursor"`
	// The working-tree overlay was active and changed the base graph.
	Dirty bool `json:"dirty"`
	// Paths the overlay fed the indexer differently from `HEAD`.
	DirtyFilesAnalyzed uint64 `json:"dirty_files_analyzed"`
	// Which tree the answer was computed over.
	Freshness FreshnessEnvelope `json:"freshness"`
	// Cache key of the graph the answer was computed over: a 7-character tree
	// OID, or `<oid>+dirty.<digest>` when the working-tree overlay changed it.
	GraphVersion string `json:"graph_version"`
	// More results exist beyond this page.
	HasMore bool        `json:"has_more"`
	Results []UnusedRow `json:"results"`
	// Size of the full result set, across all pages.
	TotalMatched uint64 `json:"total_matched"`
}

// UnusedRequest is the arguments of the "unused" tool.
type UnusedRequest struct {
	Cursor     *string `json:"cursor,omitempty"`
	Entrypoint *string `json:"entrypoint,omitempty"`
	// Default: "all".
	Kind *UnusedRequestKind `json:"kind,omitempty"`
	// Default: 20.
	MaxResults *int64 `json:"max_results,omitempty"`
}

// UnusedRequestKind is the value set of UnusedRequest.kind.
type UnusedRequestKind string

const (
	UnusedRequestKindFunction UnusedRequestKind = "function"
	UnusedRequestKindMethod   UnusedRequestKind = "method"
	UnusedRequestKindField    UnusedRequestKind = "field"
	UnusedRequestKindAll      UnusedRequestKind = "all"
)

// UnusedResult is the structuredContent of the "unused" tool.
type UnusedResult = UnusedOutput

// UnusedRow: One symbol no entrypoint reaches.
type UnusedRow struct {
	// Repo-relative definition file.
	File string `json:"file"`
	// Symbol kind.
	Kind SymbolKind `json:"kind"`
	// 1-based definition line.
	Line uint32 `json:"line"`
	// Fully qualified symbol name (opaque).
	Name string `json:"name"`
}
