// cgx-fixture: proc-macro blind spot
// Covers: #[derive(...)] -> proc-macro blind-spot cut hint (macro_origin),
//         attribute macros on functions, macro_rules! calls (resolved post-expansion)

use serde::{Serialize, Deserialize};

/// Struct with derived traits — #[derive(Serialize, Deserialize)] is a proc-macro.
/// cgx emits a cut hint: macro_origin="serde::Serialize"/"serde::Deserialize"
/// Call edges generated by the derive-expanded code are invisible to cgx
/// without cargo-expand; a blind-spot cut marker is emitted.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
    pub name: String,
    pub value: i32,
}

/// A function that uses the derived Serialize — the call to `serialize` is
/// implicit through the macro-generated impl, marked as a blind spot.
pub fn to_json(config: &Config) -> String {
    serde_json::to_string(config).unwrap_or_default()
}

/// macro_rules! — expanded inline; cgx resolves call edges after expansion.
macro_rules! double_call {
    ($f:expr, $x:expr) => {
        $f($x + $x)
    };
}

fn square(x: i32) -> i32 {
    x * x
}

/// Uses a macro_rules! macro — the call to `square` inside the expansion is
/// attributed to this call site with macro_origin="double_call".
pub fn use_macro() -> i32 {
    double_call!(square, 3)
}

/// Derive on an enum.
#[derive(Debug, Clone, PartialEq)]
pub enum Status {
    Active,
    Inactive,
    Pending(String),
}

/// tokio::main attribute macro on an async fn — proc-macro origin noted.
/// (Placed in main.rs; here we document the annotation pattern.)
pub fn describe_status(s: &Status) -> String {
    format!("{:?}", s)  // calls Debug::fmt which is proc-macro derived
}
